import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
import { CATALOG_PRODUCTS } from "../src/lib/catalog";
import {
  BLOG_IMAGES,
  CHILDREN_IMAGES,
  img,
} from "../src/lib/images";

const prisma = new PrismaClient();

const childrenProducts = [
  {
    name: "Black & White Button Dress",
    slug: "black-white-button-dress-children",
    description: "A striking half-and-half collared dress with contrast stitching, puff sleeves, and a bow belt. Perfect for parties and special occasions.",
    price: 9800,
    images: JSON.stringify([CHILDREN_IMAGES.blackWhiteButtonDress]),
    sizes: JSON.stringify(["XS", "S", "M", "L"]),
    colors: JSON.stringify(["Black & White"]),
    category: "dresses",
    ageGroup: "children",
    popularity: 90,
    isNew: true,
    isPromo: false,
  },
  {
    name: "Red Heart Two-Piece Set",
    slug: "red-heart-set-children",
    description: "Playful halter top and pleated skirt set covered in bright red hearts. A fun, coordinated look for ages 5 and up.",
    price: 8500,
    images: JSON.stringify([CHILDREN_IMAGES.redHeartSet]),
    sizes: JSON.stringify(["XS", "S", "M"]),
    colors: JSON.stringify(["Red & White"]),
    category: "dresses",
    ageGroup: "children",
    popularity: 88,
    isNew: true,
    isPromo: false,
  },
  {
    name: "Denim Pinafore Dress",
    slug: "denim-pinafore-dress-children",
    description: "Cotton denim pinafore with white puff sleeves, sweetheart neckline, and a statement bow. Sweet and durable for everyday wear.",
    price: 11200,
    images: JSON.stringify([CHILDREN_IMAGES.denimPinaforeDress]),
    sizes: JSON.stringify(["XS", "S", "M", "L"]),
    colors: JSON.stringify(["Denim Blue"]),
    category: "dresses",
    ageGroup: "children",
    popularity: 86,
    isNew: true,
    isPromo: false,
  },
  {
    name: "Pink One-Shoulder Tiered Dress",
    slug: "pink-one-shoulder-dress-children",
    description: "Textured pink one-shoulder dress with tiered ruffles and a gold flower detail. A standout piece for celebrations.",
    price: 12500,
    images: JSON.stringify([CHILDREN_IMAGES.pinkOneShoulderDress]),
    sizes: JSON.stringify(["XS", "S", "M", "L"]),
    colors: JSON.stringify(["Pink"]),
    category: "dresses",
    ageGroup: "children",
    popularity: 95,
    isNew: true,
    isPromo: true,
    promoPrice: 10500,
  },
  {
    name: "Maroon One-Shoulder Party Dress",
    slug: "maroon-one-shoulder-dress-children",
    description: "Rich maroon one-shoulder dress with gold rose brooch, bow accent, and flouncy tiered skirt.",
    price: 13200,
    images: JSON.stringify([CHILDREN_IMAGES.maroonOneShoulderDress]),
    sizes: JSON.stringify(["XS", "S", "M", "L"]),
    colors: JSON.stringify(["Maroon"]),
    category: "dresses",
    ageGroup: "children",
    popularity: 92,
    isNew: true,
    isPromo: false,
  },
  {
    name: "White Floral Off-Shoulder Dress",
    slug: "white-floral-dress-children",
    description: "White textured off-shoulder dress with embroidered floral waistband. Light, elegant, and perfect for summer events.",
    price: 11800,
    images: JSON.stringify([CHILDREN_IMAGES.whiteFloralDress]),
    sizes: JSON.stringify(["XS", "S", "M", "L"]),
    colors: JSON.stringify(["White"]),
    category: "dresses",
    ageGroup: "children",
    popularity: 89,
    isNew: false,
    isPromo: false,
  },
  {
    name: "Pink Pearl Ruffle Skirt Set",
    slug: "pink-pearl-skirt-set-children",
    description: "Coordinated white off-shoulder top with pink pearl-embellished tiered skirt, bag, and bow accessories.",
    price: 14200,
    promoPrice: 11900,
    images: JSON.stringify([CHILDREN_IMAGES.pinkPearlSkirtSet]),
    sizes: JSON.stringify(["XS", "S", "M"]),
    colors: JSON.stringify(["Pink & White"]),
    category: "dresses",
    ageGroup: "children",
    popularity: 87,
    isNew: false,
    isPromo: true,
  },
  {
    name: "Pink Bow Streetwear Set",
    slug: "pink-bow-outfit-set-children",
    description: "Trendy pink cropped hoodie, bow-print wide-leg pants, white tank, and matching accessories. Bold style for confident kids.",
    price: 15800,
    images: JSON.stringify([CHILDREN_IMAGES.pinkBowOutfitSet]),
    sizes: JSON.stringify(["S", "M", "L"]),
    colors: JSON.stringify(["Pink & White"]),
    category: "tops",
    ageGroup: "children",
    popularity: 94,
    isNew: true,
    isPromo: false,
  },
  {
    name: "Grey Star Two-Piece Set",
    slug: "grey-star-two-piece-set-children",
    description: "Casual grey heather raglan tee with black star print paired with matching wide-leg star pants. Comfortable and stylish for everyday wear.",
    price: 9200,
    images: JSON.stringify([CHILDREN_IMAGES.greyStarTwoPieceSet]),
    sizes: JSON.stringify(["XS", "S", "M", "L"]),
    colors: JSON.stringify(["Grey & Black"]),
    category: "tops",
    ageGroup: "children",
    popularity: 91,
    isNew: true,
    isPromo: false,
  },
  {
    name: "Purple Butterfly Summer Dress",
    slug: "butterfly-purple-dress-children",
    description: "Light purple dress with colorful butterfly print, ruffled cold-shoulder neckline, and waist tie bow. A dreamy summer favorite.",
    price: 10800,
    promoPrice: 8900,
    images: JSON.stringify([CHILDREN_IMAGES.butterflyPurpleDress]),
    sizes: JSON.stringify(["XS", "S", "M", "L"]),
    colors: JSON.stringify(["Purple"]),
    category: "dresses",
    ageGroup: "children",
    popularity: 93,
    isNew: true,
    isPromo: true,
  },
  {
    name: "Pink Panther Street Tee & Shorts",
    slug: "pink-panther-tee-shorts-children",
    description: "Bold black tee and shorts set with a cool pink panther graphic. A fun streetwear look for kids who love standout style.",
    price: 8900,
    images: JSON.stringify([CHILDREN_IMAGES.pinkPantherTeeShortsSet]),
    sizes: JSON.stringify(["XS", "S", "M", "L"]),
    colors: JSON.stringify(["Black"]),
    category: "tops",
    ageGroup: "children",
    popularity: 96,
    isNew: true,
    isPromo: false,
  },
  {
    name: "Geometric Orange Shirt & Shorts Set",
    slug: "geometric-orange-set-children",
    description: "Modern geometric print short-sleeve shirt layered over a white tee, paired with matching orange drawstring shorts.",
    price: 9500,
    images: JSON.stringify([CHILDREN_IMAGES.geometricOrangeShirtShortsSet]),
    sizes: JSON.stringify(["XS", "S", "M", "L"]),
    colors: JSON.stringify(["Orange & White"]),
    category: "tops",
    ageGroup: "children",
    popularity: 88,
    isNew: true,
    isPromo: false,
  },
  {
    name: "Boston 23 Graphic Tee & Shorts",
    slug: "boston-23-set-children",
    description: "White Boston 23 graphic tee with matching black shorts. Sporty varsity style for everyday wear.",
    price: 7800,
    images: JSON.stringify([CHILDREN_IMAGES.boston23TeeShortsSet]),
    sizes: JSON.stringify(["XS", "S", "M", "L", "XL"]),
    colors: JSON.stringify(["White & Black"]),
    category: "tops",
    ageGroup: "children",
    popularity: 90,
    isNew: false,
    isPromo: false,
  },
  {
    name: "Street Duck Graphic Tee",
    slug: "street-duck-tee-children",
    description: "Black crew-neck tee with a bold cartoon duck street graphic. A statement piece for casual outfits.",
    price: 5500,
    images: JSON.stringify([CHILDREN_IMAGES.streetDuckGraphicTee]),
    sizes: JSON.stringify(["XS", "S", "M", "L"]),
    colors: JSON.stringify(["Black"]),
    category: "tops",
    ageGroup: "children",
    popularity: 85,
    isNew: true,
    isPromo: false,
  },
  {
    name: "Chicago 26 Freedom Two-Piece Set",
    slug: "chicago-26-freedom-set-children",
    description: "Coordinated white Freedom 26 Chicago tee with black athletic shorts. Clean streetwear for active kids.",
    price: 8200,
    images: JSON.stringify([CHILDREN_IMAGES.chicago26FreedomSet]),
    sizes: JSON.stringify(["S", "M", "L", "XL"]),
    colors: JSON.stringify(["White & Black"]),
    category: "tops",
    ageGroup: "children",
    popularity: 92,
    isNew: true,
    isPromo: false,
  },
  {
    name: "Designer Monogram Kids Set",
    slug: "designer-monogram-set-children",
    description: "Premium-inspired monogram tee and patterned shorts set. Stylish coordinated look with signature stripe details.",
    price: 13500,
    promoPrice: 6750,
    images: JSON.stringify([CHILDREN_IMAGES.designerMonogramKidsSet]),
    sizes: JSON.stringify(["XS", "S", "M", "L"]),
    colors: JSON.stringify(["Cream & Tan"]),
    category: "tops",
    ageGroup: "children",
    popularity: 97,
    isNew: false,
    isPromo: true,
  },
  {
    name: "Chicago 32 Sports Two-Piece Set",
    slug: "chicago-32-sports-set-children",
    description: "Color-block Chicago 32 tee and matching shorts with varsity stripes. Sport-ready street style for ages 5+.",
    price: 8800,
    images: JSON.stringify([CHILDREN_IMAGES.chicago32SportsSet]),
    sizes: JSON.stringify(["XS", "S", "M", "L"]),
    colors: JSON.stringify(["Black & White"]),
    category: "tops",
    ageGroup: "children",
    popularity: 94,
    isNew: true,
    isPromo: false,
  },
  // Children — bottoms, outerwear & accessories (online stock photos)
  {
    name: "Kids Stretch Denim Jeans",
    slug: "kids-stretch-jeans-children",
    description: "Soft stretch denim jeans built for active play and everyday comfort.",
    price: 6500,
    images: JSON.stringify([img("photo-1542272604-787c683553e0")]),
    sizes: JSON.stringify(["XS", "S", "M", "L"]),
    colors: JSON.stringify(["Blue", "Black"]),
    category: "bottoms",
    ageGroup: "children",
    popularity: 84,
    isNew: false,
    isPromo: false,
  },
  {
    name: "Kids Cargo Joggers",
    slug: "kids-cargo-joggers-children",
    description: "Relaxed cargo joggers with elastic waist — easy on, easy off.",
    price: 5800,
    images: JSON.stringify([img("photo-1624378515199-75dbbefe4ff3")]),
    sizes: JSON.stringify(["XS", "S", "M", "L"]),
    colors: JSON.stringify(["Khaki", "Olive"]),
    category: "bottoms",
    ageGroup: "children",
    popularity: 82,
    isNew: true,
    isPromo: false,
  },
  {
    name: "Kids Pleated School Skirt",
    slug: "kids-pleated-skirt-children",
    description: "Classic pleated skirt for school uniforms and dressy days.",
    price: 5200,
    images: JSON.stringify([img("photo-1583496669740-3485d9fbf1ae")]),
    sizes: JSON.stringify(["XS", "S", "M"]),
    colors: JSON.stringify(["Navy", "Grey"]),
    category: "bottoms",
    ageGroup: "children",
    popularity: 80,
    isNew: false,
    isPromo: false,
  },
  {
    name: "Kids Athletic Shorts",
    slug: "kids-athletic-shorts-children",
    description: "Breathable athletic shorts for sports and summer play.",
    price: 3800,
    images: JSON.stringify([img("photo-1541099649105-f69ad21f3246")]),
    sizes: JSON.stringify(["XS", "S", "M", "L"]),
    colors: JSON.stringify(["Black", "Navy", "Red"]),
    category: "bottoms",
    ageGroup: "children",
    popularity: 78,
    isNew: false,
    isPromo: false,
  },
  {
    name: "Kids Wide Leg Pants",
    slug: "kids-wide-leg-pants-children",
    description: "Comfortable wide-leg pants with a soft elastic waistband.",
    price: 6200,
    promoPrice: 4900,
    images: JSON.stringify([img("photo-1503919028437-b9f291a629f0")]),
    sizes: JSON.stringify(["XS", "S", "M", "L"]),
    colors: JSON.stringify(["Beige", "Black"]),
    category: "bottoms",
    ageGroup: "children",
    popularity: 81,
    isNew: false,
    isPromo: true,
  },
  {
    name: "Kids Denim Jacket",
    slug: "kids-denim-jacket-children",
    description: "Classic denim jacket sized for kids — perfect for layering.",
    price: 9800,
    images: JSON.stringify([img("photo-1576995850633-9663eaa5131b")]),
    sizes: JSON.stringify(["XS", "S", "M", "L"]),
    colors: JSON.stringify(["Light Wash", "Indigo"]),
    category: "outerwear",
    ageGroup: "children",
    popularity: 86,
    isNew: true,
    isPromo: false,
  },
  {
    name: "Kids Fleece Zip Hoodie",
    slug: "kids-fleece-hoodie-children",
    description: "Warm fleece zip hoodie for school mornings and cool evenings.",
    price: 8500,
    images: JSON.stringify([img("photo-1556821840-3a63f95609a7")]),
    sizes: JSON.stringify(["XS", "S", "M", "L"]),
    colors: JSON.stringify(["Grey", "Navy", "Pink"]),
    category: "outerwear",
    ageGroup: "children",
    popularity: 88,
    isNew: false,
    isPromo: false,
  },
  {
    name: "Kids Puffer Vest",
    slug: "kids-puffer-vest-children",
    description: "Lightweight quilted vest for extra warmth without bulk.",
    price: 7200,
    images: JSON.stringify([img("photo-1544966503-d8e8fda57722")]),
    sizes: JSON.stringify(["XS", "S", "M", "L"]),
    colors: JSON.stringify(["Black", "Red"]),
    category: "outerwear",
    ageGroup: "children",
    popularity: 79,
    isNew: false,
    isPromo: false,
  },
  {
    name: "Kids Rain Anorak",
    slug: "kids-rain-anorak-children",
    description: "Water-resistant anorak with a hood for rainy day adventures.",
    price: 9200,
    images: JSON.stringify([img("photo-1543076447-215a9eea3647")]),
    sizes: JSON.stringify(["XS", "S", "M", "L"]),
    colors: JSON.stringify(["Yellow", "Navy"]),
    category: "outerwear",
    ageGroup: "children",
    popularity: 77,
    isNew: true,
    isPromo: false,
  },
  {
    name: "Kids Wool Blend Coat",
    slug: "kids-wool-coat-children",
    description: "Smart wool-blend coat for formal events and winter outings.",
    price: 14500,
    promoPrice: 11800,
    images: JSON.stringify([img("photo-1539533018447-63fcce267834")]),
    sizes: JSON.stringify(["XS", "S", "M", "L"]),
    colors: JSON.stringify(["Camel", "Navy"]),
    category: "outerwear",
    ageGroup: "children",
    popularity: 83,
    isNew: false,
    isPromo: true,
  },
  {
    name: "Kids Canvas Backpack",
    slug: "kids-canvas-backpack-children",
    description: "Durable canvas backpack with padded straps for school.",
    price: 6500,
    images: JSON.stringify([img("photo-1584917865442-de89d76adc7e")]),
    sizes: JSON.stringify(["One Size"]),
    colors: JSON.stringify(["Blue", "Pink", "Black"]),
    category: "accessories",
    ageGroup: "children",
    popularity: 85,
    isNew: false,
    isPromo: false,
  },
  {
    name: "Kids Sport Cap",
    slug: "kids-sport-cap-children",
    description: "Adjustable cotton cap for sun protection and sporty style.",
    price: 2800,
    images: JSON.stringify([img("photo-1588850561407-ed78c282e89b")]),
    sizes: JSON.stringify(["One Size"]),
    colors: JSON.stringify(["Navy", "White", "Red"]),
    category: "accessories",
    ageGroup: "children",
    popularity: 74,
    isNew: false,
    isPromo: false,
  },
  {
    name: "Kids Sunglasses",
    slug: "kids-sunglasses-children",
    description: "Flexible frame sunglasses with UV400 protection.",
    price: 3200,
    images: JSON.stringify([img("photo-1572635196237-14b3f281503f")]),
    sizes: JSON.stringify(["One Size"]),
    colors: JSON.stringify(["Black", "Tortoise"]),
    category: "accessories",
    ageGroup: "children",
    popularity: 72,
    isNew: true,
    isPromo: false,
  },
  {
    name: "Kids Hair Bow Set",
    slug: "kids-hair-bow-set-children",
    description: "Pack of satin hair bows in assorted colors.",
    price: 2200,
    images: JSON.stringify([img("photo-1611591436351-75b3e8ab1a1e")]),
    sizes: JSON.stringify(["One Size"]),
    colors: JSON.stringify(["Pink", "White", "Red"]),
    category: "accessories",
    ageGroup: "children",
    popularity: 80,
    isNew: true,
    isPromo: false,
  },
  {
    name: "Kids Velcro Sneakers",
    slug: "kids-velcro-sneakers-children",
    description: "Easy velcro-strap sneakers for active kids on the go.",
    price: 8900,
    promoPrice: 7100,
    images: JSON.stringify([img("photo-1542291026-7eec264c27ff")]),
    sizes: JSON.stringify(["28", "30", "32", "34"]),
    colors: JSON.stringify(["White", "Pink", "Navy"]),
    category: "accessories",
    ageGroup: "children",
    popularity: 87,
    isNew: false,
    isPromo: true,
  },
];

const products = [...childrenProducts, ...CATALOG_PRODUCTS];

const blogPosts = [
  {
    title: "5 Ways to Style Layered Looks This Season",
    slug: "style-layered-looks-season",
    excerpt: "Master the art of layering with Temir pieces that work across every age group.",
    content: "Layering is the secret to transitional dressing. Start with a breathable base, add texture with knits or hoodies, and finish with structured outerwear. Mix soft neutrals from our cream and sage palette for a cohesive, family-friendly wardrobe.",
    image: BLOG_IMAGES.layeredLooks,
  },
  {
    title: "Choosing the Right Fit for Growing Kids",
    slug: "right-fit-growing-kids",
    excerpt: "Comfort meets durability — our guide to sizing children's clothing.",
    content: "Children grow quickly, so look for adjustable waistbands and stretch fabrics. Temir children's line uses soft cotton blends that move with active play while maintaining shape after every wash.",
    image: CHILDREN_IMAGES.denimPinaforeDress,
  },
  {
    title: "Temir Spring Collection: What's New",
    slug: "temir-spring-collection-new",
    excerpt: "Discover fresh arrivals designed for children, teens, youths, and adults.",
    content: "Our Spring collection celebrates soft colors and versatile silhouettes. From playground-ready joggers to executive blazers, every piece is crafted to feel premium without compromising everyday wearability.",
    image: BLOG_IMAGES.springCollection,
  },
];

async function main() {
  const existingProducts = await prisma.product.count();
  if (existingProducts > 0) {
    console.log("Database already has products — skipping seed.");
    return;
  }

  await prisma.cartItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.newsletter.deleteMany();
  await prisma.blogPost.deleteMany();
  await prisma.product.deleteMany();
  await prisma.user.deleteMany();

  const passwordHash = await bcrypt.hash("demo1234", 12);
  await prisma.user.create({
    data: {
      email: "demo@temir.com",
      passwordHash,
      name: "Demo User",
      phone: "+234 800 000 0000",
      address: "12 Fashion Avenue",
      city: "Lagos",
      state: "Lagos",
      zip: "100001",
      country: "Nigeria",
    },
  });

  for (const product of products) {
    await prisma.product.create({ data: product });
  }

  for (const post of blogPosts) {
    await prisma.blogPost.create({ data: post });
  }

  console.log(`Database seeded: ${childrenProducts.length} children + ${CATALOG_PRODUCTS.length} teen/youth/adult products.`);
  console.log("Demo login: demo@temir.com / demo1234");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
